#!/usr/bin/env python3
"""OpenRecomp Phase-8 static memory and runtime contract gate (P8-05).

P8-05 validates the frozen real ELF's required static memory and runtime
contract, reusing the existing guest-image ingestion and generic runtime ABI
architecture:

* executable memory, `.rodata`, initialized `.data`, zero-filled `.bss`;
* the 16 KiB static stack and its top address;
* bounded guest memory access with explicit region permissions;
* the single write-only byte output host service and return-to-host
  termination (no Linux kernel emulation, no dynamic linking).

The gate generates the deterministic image translation unit, compiles a
native memory-contract driver against the OpenRecomp-authored runtime support,
and differentially verifies read/write outcomes against an independently
written Python memory model over an explicit access vector.

On success it emits::

    OPENRECOMP_P8_05=PASS
    OPENRECOMP_PHASE8_RUNTIME_CONTRACT_V1=PASS tests=<count>
    OPENRECOMP_PHASE8_MIPS32_END_TO_END_NATIVE_PROOF=NOT_PROVEN
    OPENRECOMP_PHASE8_GENERAL_MIPS32_COMPATIBILITY=NOT_PROVEN

Usage:

    python tools/test_phase8_runtime_v1.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import shutil
import subprocess
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / ".openrecomp-phase3" / "src"))
sys.path.insert(0, str(ROOT / ".openrecomp-phase8" / "src"))

import p3_code_frontier_v1 as frontier  # noqa: E402
import p3_elf_image_v1 as elf  # noqa: E402
import p3_target_mips32_v1 as target  # noqa: E402
import p8_memory_contract_v1 as contract_v1  # noqa: E402
from openrecomp import build_pipeline as bp  # noqa: E402

EVIDENCE_DIR = ROOT / ".openrecomp-phase8" / "evidence" / "P8-05"
WORKSPACE = ROOT / ".openrecomp-phase8" / "build" / "P8-05"
SUPPORT_SOURCE = ROOT / ".openrecomp-phase8" / "runtime" / "p8_runtime_support.c"

STAGE = "P8-05"
STAGE_MARKER = "OPENRECOMP_P8_05"
FEATURE_MARKER = "OPENRECOMP_PHASE8_RUNTIME_CONTRACT_V1"
TERMINAL_MARKER = "OPENRECOMP_PHASE8_MIPS32_END_TO_END_NATIVE_PROOF"
GENERAL_MARKER = "OPENRECOMP_PHASE8_GENERAL_MIPS32_COMPATIBILITY"
NOT_PROVEN = "NOT_PROVEN"

FIXTURE_ELF = ROOT / ".openrecomp-phase8" / "build" / "P8-01" / "candidate-a" / "p8_aes128_mips32_O1.elf"
FIXTURE_SHA256 = "0a90f47754f6331b868ec09ad23c451fc2c73925a43897fa62a696b0d40dde65"

EXPECTED_REGIONS = (
    ("load_0", 0x0, 244, "r--"),
    ("load_1", 0x1000, 5300, "r-x"),
    ("load_2", 0x24C0, 571, "r--"),
    ("load_3", 0x2700, 16400, "rw-"),
)
EXPECTED_SECTIONS = {
    ".text": (0x1000, 5300, "r-x"),
    ".rodata": (0x24C0, 571, "r--"),
    ".data": (0x2700, 8, "rw-"),
    ".bss": (0x2710, 16384, "rw-"),
}
EXPECTED_STACK = {"base": 0x2710, "size": 16384, "top": 0x6710}
EXPECTED_IMAGE_SIZE = 0x6710

# (name, address, width_bits, value) -- writes applied in order.
WRITE_VECTOR = (
    ("write-data", 0x2700, 32, 0x12345678),
    ("write-bss", 0x2710, 8, 0xAB),
    ("write-halfword", 0x2712, 16, 0xBEEF),
    ("write-text-denied", 0x1000, 32, 0x11),
    ("write-rodata-denied", 0x24C0, 8, 0x22),
    ("write-out-of-range", EXPECTED_IMAGE_SIZE, 8, 0x33),
    ("write-unsupported-width", 0x2700, 64, 0x44),
    ("write-output-byte", contract_v1.OUTPUT_ADDRESS, 8, 0x41),
    ("write-output-word-denied", contract_v1.OUTPUT_ADDRESS, 32, 0x42),
)
# (name, address, width_bits) -- reads after the writes.
READ_VECTOR = (
    ("read-text", 0x1000, 32),
    ("read-rodata", 0x24C0, 8),
    ("read-data", 0x2700, 32),
    ("read-bss", 0x2710, 8),
    ("read-halfword", 0x2712, 16),
    ("read-out-of-range", EXPECTED_IMAGE_SIZE, 8),
    ("read-unsupported-width", 0x1000, 64),
    ("read-output-denied", contract_v1.OUTPUT_ADDRESS, 8),
)

RESULTS: list[dict[str, str]] = []


def check(label: str, condition: bool, detail: str = "") -> None:
    if not condition:
        RESULTS.append({"check": label, "status": "FAIL", "detail": detail})
        raise AssertionError(f"{label}: condition failed ({detail})")
    RESULTS.append({"check": label, "status": "PASS", "detail": detail})
    print(f"PASS: {label}")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def evidence_json(payload: object) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def write_evidence(name: str, payload: object) -> None:
    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    (EVIDENCE_DIR / name).write_bytes(evidence_json(payload))


def driver_source() -> str:
    lines = [
        "/* OpenRecomp Phase 8 memory-contract driver (generated by the P8-05 gate). */",
        "#include <stdio.h>",
        "#include <stdint.h>",
        "",
        "int or_rt_memory_read(uint64_t address, uint32_t width_bits, uint64_t *out_value);",
        "int or_rt_memory_write(uint64_t address, uint32_t width_bits, uint64_t value);",
        "void p8_runtime_init(void);",
        "uint64_t p8_runtime_memory_reads(void);",
        "uint64_t p8_runtime_memory_writes(void);",
        "uint64_t p8_runtime_denied_accesses(void);",
        "uint64_t p8_runtime_host_calls(void);",
        "uint64_t p8_runtime_transcript_length(void);",
        "const unsigned char *p8_runtime_transcript(void);",
        "",
        "int main(void) {",
        "    uint64_t value = 0;",
        "    int status = 0;",
        "    p8_runtime_init();",
    ]
    for name, address, width, written in WRITE_VECTOR:
        lines.append(f'    value = UINT64_C({written});')
        lines.append(
            f'    status = or_rt_memory_write(UINT64_C({address}), {width}u, value);'
        )
        lines.append(f'    printf("write:{name}=%d\\n", status);')
    for name, address, width in READ_VECTOR:
        lines.append(f'    value = UINT64_C(0);')
        lines.append(
            f'    status = or_rt_memory_read(UINT64_C({address}), {width}u, &value);'
        )
        lines.append(f'    printf("read:{name}=%d:%llu\\n", status, (unsigned long long)value);')
    lines.extend(
        [
            '    printf("counters:%llu:%llu:%llu:%llu\\n",',
            "        (unsigned long long)p8_runtime_memory_reads(),",
            "        (unsigned long long)p8_runtime_memory_writes(),",
            "        (unsigned long long)p8_runtime_denied_accesses(),",
            "        (unsigned long long)p8_runtime_host_calls());",
            '    printf("transcript:%llu", (unsigned long long)p8_runtime_transcript_length());',
            "    for (uint64_t index = 0; index < p8_runtime_transcript_length(); ++index) {",
            '        printf(":%02x", (unsigned)p8_runtime_transcript()[index]);',
            "    }",
            '    printf("\\n");',
            "    return 0;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    try:
        data = FIXTURE_ELF.read_bytes()
        check("fixture:sha256", sha256_bytes(data) == FIXTURE_SHA256, sha256_bytes(data))

        ingested = elf.ingest(data, target.MIPS32_O32)
        image = contract_v1.flat_image(ingested)
        contract = contract_v1.build_contract(ingested)
        check("image:size", contract["image_size"] == EXPECTED_IMAGE_SIZE, hex(contract["image_size"]))
        check("image:sha256-stable", contract_v1.sha256_bytes(image) == contract["image_sha256"], contract["image_sha256"])
        for name, base, size, permissions in EXPECTED_REGIONS:
            observed = next(region for region in contract["regions"] if region["name"] == name)
            check(
                f"region:{name}",
                observed["base"] == base and observed["size"] == size and observed["permissions"] == permissions,
                json.dumps(observed, sort_keys=True),
            )
        for name, (base, size, permissions) in sorted(EXPECTED_SECTIONS.items()):
            observed = next(section for section in contract["sections"] if section["name"] == name)
            check(
                f"section:{name}",
                observed["base"] == base and observed["size"] == size and observed["permissions"] == permissions,
                json.dumps(observed, sort_keys=True),
            )
        stack = contract["stack"]
        check("stack:identity", stack["base"] == EXPECTED_STACK["base"] and stack["size"] == EXPECTED_STACK["size"] and stack["top"] == EXPECTED_STACK["top"], json.dumps(stack, sort_keys=True))
        check("stack:inside-bss", stack["base"] == EXPECTED_SECTIONS[".bss"][0] and stack["top"] <= EXPECTED_IMAGE_SIZE, "stack-in-bss")

        # .bss zero-fill proof: NOBITS content is zero even where file bytes are not
        bss = next(section for section in contract["sections"] if section["name"] == ".bss")
        zero_fill = image[bss["base"] : bss["base"] + bss["size"]]
        check("bss:image-zero-fill", zero_fill == bytes(bss["size"]), sha256_bytes(zero_fill))
        check("bss:not-file-backed", bss["kind"] == "ZERO_FILL", bss["kind"])
        data_section = next(section for section in contract["sections"] if section["name"] == ".data")
        check("data:initialized", image[data_section["base"] : data_section["base"] + data_section["size"]] == bytes.fromhex("0000000000000080"), image[data_section["base"] : data_section["base"] + 8].hex())
        rodata = next(section for section in contract["sections"] if section["name"] == ".rodata")
        check("rodata:file-backed", rodata["kind"] == "FILE_BACKED" and rodata["sha256"] == contract_v1.sha256_bytes(ingested.image.section_bytes(".rodata")), rodata["sha256"])

        # reachable memory accesses are register-based, bounded, and never GP-relative
        region = ingested.parsed.executable_regions()[0]
        analysis = frontier.analyze(ingested.image.read_u32, region.p_vaddr, region.p_vaddr + region.p_memsz, ingested.parsed.header.e_entry)
        records = {record["address"]: record for record in analysis["records"]}
        accesses = [record for address, record in records.items() if address in set(analysis["reachable_addresses"]) and record["op"] in ("lw", "sw", "lb", "lbu", "sb")]
        check("access:count", len(accesses) == 270, str(len(accesses)))
        check("access:all-register-based", all(record["terminator"] is None for record in accesses), "no absolute addressing")
        gp_accesses = [record for record in accesses if record["operands"].get("rs") == 28]
        check("access:no-gp-relative", gp_accesses == [], str(len(gp_accesses)))
        widths = {}
        for record in accesses:
            widths[record["op"]] = widths.get(record["op"], 0) + 1
        check("access:widths", set(widths) == {"lw", "sw", "lb", "lbu", "sb"}, json.dumps(widths, sort_keys=True))
        sp_accesses = [record for record in accesses if record["operands"].get("rs") == 29]
        max_sp_offset = max(abs(record["operands"].get("imm", 0)) for record in sp_accesses)
        check("access:stack-bounded", len(sp_accesses) == 48 and max_sp_offset == 0x104, f"sp={len(sp_accesses)} max_offset=0x{max_sp_offset:x}")

        # runtime/host contract
        check("contract:host-services", contract["host_services"] == [{"id": contract_v1.OUTPUT_SERVICE, "arg_count": 1}], json.dumps(contract["host_services"]))
        check("contract:output-window", contract["output_window"]["address"] == contract_v1.OUTPUT_ADDRESS and contract["output_window"]["width_bits"] == 8, json.dumps(contract["output_window"], sort_keys=True))
        check("contract:termination", contract["termination"]["kind"] == "guest-return-to-host" and contract["termination"]["sentinel"] == 0, json.dumps(contract["termination"], sort_keys=True))
        check("contract:no-kernel", contract["kernel_emulation"] == "not-required", contract["kernel_emulation"])
        check("contract:static-no-dynamic", contract["static"] is True and contract["dynamic"] is False and contract["relocations"] is False, "static")
        check("contract:no-system-traps", analysis["summary"]["exception_site_count"] == 0 and analysis["control_flow"]["unsupported-control-transfers"] == [], "no syscall/break")

        # deterministic generated image translation unit
        header_a = contract_v1.render_image_header(contract)
        header_b = contract_v1.render_image_header(contract)
        source_a = contract_v1.render_image_source(contract, image)
        source_b = contract_v1.render_image_source(contract, image)
        check("image-c:deterministic", header_a == header_b and source_a == source_b, sha256_bytes(source_a.encode("utf-8")))
        check("image-c:no-host-paths", "D:" not in source_a and "C:" not in source_a, "portable")
        check("image-c:declares-image", "const unsigned char p8_image[P8_IMAGE_SIZE]" in source_a and "p8_regions" in source_a, "generated")

        # native differential memory-contract test
        if WORKSPACE.exists():
            shutil.rmtree(WORKSPACE)
        WORKSPACE.mkdir(parents=True, exist_ok=True)
        image_unit, support_unit = contract_v1.compose_runtime_sources(contract, image, SUPPORT_SOURCE.read_text(encoding="utf-8"))
        comparison = bp.build_generated_host(
            lambda: driver_source(),
            support_sources=(
                bp.BuildSource(image_unit[0], bp.BuildArtifactKind.RUNTIME_SUPPORT_SOURCE, image_unit[1].encode("utf-8")),
                bp.BuildSource(support_unit[0], bp.BuildArtifactKind.RUNTIME_SUPPORT_SOURCE, support_unit[1].encode("utf-8")),
            ),
            config=bp.BuildConfig(fixture_id="p8-05-memory-contract", smoke_test=False, run_count=2, reproducible=False),
            workspace=WORKSPACE,
            keep_workspace=True,
        )
        check("native:build-ok", all(run.manifest.build_status is bp.BuildStatus.OK for run in comparison.runs), "ok")
        executable = WORKSPACE / "run1" / "program.exe"
        ran = subprocess.run([str(executable)], capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=600)
        check("native:exit-code", ran.returncode == 0, str(ran.returncode))

        model = contract_v1.PythonMemoryModel(contract, image)
        expected: dict[str, str] = {}
        for name, address, width, value in WRITE_VECTOR:
            expected[f"write:{name}"] = str(model.write(address, width, value))
        for name, address, width in READ_VECTOR:
            status, value = model.read(address, width)
            expected[f"read:{name}"] = f"{status}:{value}"
        observed: dict[str, str] = {}
        counters: dict[str, int] = {}
        transcript: list[int] = []
        transcript_length = -1
        for line in ran.stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            if line.startswith(("write:", "read:")) and "=" in line:
                key, value = line.split("=", 1)
                observed[key] = value
            elif line.startswith("counters:") and ":" in line:
                _, *values = line.split(":")
                counters = dict(zip(("reads", "writes", "denied", "host_calls"), (int(item) for item in values)))
            elif line.startswith("transcript:") and ":" in line:
                _, length, *values = line.split(":")
                transcript = [int(item, 16) for item in values]
                transcript_length = int(length)
        check("differential:outcomes-equal-python-model", observed == expected, json.dumps({"native": observed, "reference": expected}, sort_keys=True))
        expected_counters = {
            "reads": sum(1 for name, _, _ in READ_VECTOR if expected[f"read:{name}"].startswith("0:")),
            "writes": sum(
                1
                for name, address, _, _ in WRITE_VECTOR
                if expected[f"write:{name}"] == "0" and address != contract_v1.OUTPUT_ADDRESS
            ),
            "denied": sum(
                1
                for key, value in expected.items()
                if (key.startswith("write:") and value != "0")
                or (key.startswith("read:") and not value.startswith("0:"))
            ),
            "host_calls": 1,
        }
        check("native:counters", counters == expected_counters, json.dumps({"native": counters, "expected": expected_counters}, sort_keys=True))
        check(
            "native:transcript",
            transcript == model.transcript and transcript == [0x41] and transcript_length == 1,
            json.dumps({"transcript": transcript, "length": transcript_length}),
        )

        write_evidence(
            "memory_contract.json",
            {
                "stage": STAGE,
                "fixture": {"sha256": FIXTURE_SHA256},
                "contract": contract,
                "contract_digest": contract_v1.contract_digest(contract),
                "generated_image_c": {
                    "header_sha256": sha256_bytes(header_a.encode("utf-8")),
                    "source_sha256": sha256_bytes(source_a.encode("utf-8")),
                    "source_bytes": len(source_a.encode("utf-8")),
                },
                "access_model": {
                    "reachable_memory_accesses": len(accesses),
                    "op_histogram": widths,
                    "sp_relative": len(sp_accesses),
                    "max_sp_offset": max_sp_offset,
                    "gp_relative": len(gp_accesses),
                },
                "differential": {"native": observed, "python_model": expected, "counters": counters, "transcript": transcript},
                "markers": {
                    "terminal": f"{TERMINAL_MARKER}={NOT_PROVEN}",
                    "general": f"{GENERAL_MARKER}={NOT_PROVEN}",
                },
            },
        )
    except Exception as exc:  # stable fail-closed boundary
        RESULTS.append({"check": "gate:exception", "status": "FAIL", "detail": f"{type(exc).__name__}: {exc}"})

    status = "PASS" if all(item["status"] == "PASS" for item in RESULTS) else "FAIL"
    record = {
        "stage": STAGE,
        "stage_name": "Static memory and runtime contract closure",
        "status": status,
        "tests": len(RESULTS),
        "passed": sum(1 for item in RESULTS if item["status"] == "PASS"),
        "failed": sum(1 for item in RESULTS if item["status"] != "PASS"),
        "checks": RESULTS,
        "failure": None if status == "PASS" else [item for item in RESULTS if item["status"] != "PASS"],
        "markers": {
            "stage": f"{STAGE_MARKER}={status}",
            "gate": f"{FEATURE_MARKER}={status} tests={len(RESULTS)}",
            "terminal": f"{TERMINAL_MARKER}={NOT_PROVEN}",
            "general": f"{GENERAL_MARKER}={NOT_PROVEN}",
        },
    }
    write_evidence("p8_05_tests.json", record)

    for item in RESULTS:
        if item["status"] != "PASS":
            print(f"FAIL: {item['check']} :: {item.get('detail', '')}")
    print(f"{STAGE_MARKER}={status}")
    print(f"{FEATURE_MARKER}={status} tests={len(RESULTS)}")
    print(f"{TERMINAL_MARKER}={NOT_PROVEN}")
    print(f"{GENERAL_MARKER}={NOT_PROVEN}")
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
